import React, { Component } from 'react';
import { appStyles, colors, fontSize } from '../../themes';
import { BackIcon } from '../../components';
import { height } from 'react-native-dimension';
import { StyleSheet } from 'react-native';

const baseURL = 'https://bodework-backend.herokuapp.com/api/';
// const mapKey = "AIzaSyCN_YkscFux2VKEqvm9lco3B-NLVAMgC8Q";
   const mapKey = "AIzaSyBYrhwDLjzAji73YKhXj_xO1ODCMKwXjtk";

const endPoints = {
  login: 'user-login',
  signUp: 'user-register',
  passwordreset: 'password-reset',
  userProfile: 'show-user-profile',
  updateProfile: 'update-user',
  pauseAccount: 'pause-account',
  changePassword: 'change-password',
  showAbout: 'show-about',
  addAbout: 'add-about',
  updateAbout: 'update-about',
  // showServices: 'show-services',
  favouriteStylers: 'show-favorite-stylists',
  pastStylers: 'show-stylist-past-booking',
  notifications: 'show-notifications',
  termsAndCondition: 'show-terms-conditions',
  privacyPolicy: 'show-privacy-policy',
  getfaqs: 'get-faqs',
  cancelationPolicy: 'show-cancellation-policy',
  legalNotices: 'show-legal-notices',
  scheduleBookings: 'show-user-schedule-booking',
  completedBookings: 'show-user-past-booking',
  postReview: 'stylist-post-review',
  showskills:'show-skills',
  showservices:'show-services',
  stylisthome:'stylist-home',
  showstylistschedulbooking:'show-stylist-schedule-booking',
  showstylistpastbooking:"show-stylist-past-booking",
  showfeatureservices:'show-feature-services',
  searchclients:"search-clients",
  makereservation:"make-reservation",
  addservice:'add-service',
  stylistaddservice:"stylist-add-service",
  stylisteditservice:'stylist-edit-service',
  deleteservice:"delete-service",
  showportfolio:"show-portfolio",
  addportfolio:'add-portfolio',
  monthlyreports:'monthly-reports',
  weeklyreports:'weekly-reports',
  showstylistreviews:'show-stylist-reviews',
  stylistpostreview:'stylist-post-review',
  stylistservices:'stylist-services',
  showstylists:'show-stylists',
  addfavoritestylist:'add-favorite-stylist',
  removefavoritestylist:'remove-favorite-stylist',
  showstylistprofile:'show-stylist-profile',
  makebooking:'make-booking',
  cancelbooking:'cancel-booking',
  startjob:'start-job',
  completejob:'complete-job',
  userpostreview:'user-post-review',
  showmessages:'show-messages',
  showconversation:'show-conversation',
  sendmessage:'send-message',
  showavailability:'show-availability',
  createimeslot:'create-timeslot',
  searchservices:'search-services',
  sendcustomersupport:'send-customer-support',
  addcard:'add-card',
  addbankdetails:'add-bank-details',
  addclosingmessage:'add-closing-message',
  showhomeservices:'show-home-services',
  showstylistservices:'show-stylist-services',
  uploadidentity:'upload-identity',
  addavailability:'add-availability',
  showallavailabilities:'show-all-availabilities',
  addvacation:'add-vacation',
  stylistservices:'stylist-services',
  createtimeslot:'create-timeslot',
  adjustcominghours:'adjust-coming-hours',
  monthlybookings:'monthly-bookings',
  getbydatebookings:'get-by-date-bookings',
  getbookingrequests:'get-booking-requests',
  acceptbookingrequest:'accept-booking-request',
  showclients:'show-clients',
  userlogout:'user-logout',
};

const header = {
  screenOptions: {
    //  headerShown: false,
    title: 'Title',
    headerTitleAlign: 'left',
    headerStyle: [appStyles.headerStyle],
    headerTitleStyle: appStyles.headerTitleStyle,
    headerTintColor: colors.appTextColor4,
    headerBackImage: () => <BackIcon />,
    headerBackTitle: ' ',
  },
  screenOptions2: {
    //  headerShown: false,
    title: 'Title',
    headerTitleAlign: 'center',
    headerStyle: [appStyles.materialHeaderStyle],
    headerTitleStyle: appStyles.materialHeaderTitleStyle,
    headerTintColor: colors.appTextColor6,
    headerBackImage: () => <BackIcon />,
    headerBackTitle: ' ',
  },
};

const routes = {
  auth: 'Auth',
  clientApp: 'clientApp',
  providerApp: 'providerApp',
  authHome: 'authHome',
  signInUp: 'signInUp',
  signin: 'signin',
  signup: 'signup',
  resetPassword: 'resetPassword',
  // Provider auth screens routes
  identityproof: 'identityproof',
  services: 'services',
  priceList: 'priceList',
  pricenewList: 'pricenewList',
  workLicense: 'workLicense',
  createService:"createService",
  terms: 'terms',
  stylistdetails:"stylistdetails",
  changelocation:'changelocation',

  client: {
    mainTab: 'clientMainTab',
    homeTab: 'clientHomeTab',
    availablilityTab: 'availablilityTab',
    manageOngoingAvailability: 'manageOngoingAvailability',
    manageVacationTime: 'manageVacationTime',
    adjustComingHour: 'adjustComingHour',
    profile: 'Profile',
    searchClient: 'searchClient',
    services: 'services',
    selectDate: 'selectDate',
    charges: 'charges',
    businessPhoto: 'businessPhoto',
    addSkills: 'addSkills',
    editSkills: 'editSkills',
    setRate: 'setRate',
    support: 'support',
    faq: 'faq',
    privacyPolicy: 'privacyPolicy',
    termsAndCondition: 'termsAndCondition',
    acknowledgements: 'acknowledgements',
    jobDetail: 'jobDetail',
    selectStylish: 'selectStylish',

    myBusinessTab: 'myBusinessTab',
    servicesTab: 'clientServicesTab',
    stylersTab: 'clientStylersTab',
    profileTab: 'clientProfileTab',
    home: 'clientHome',
    ProfileView: 'profileview',
    notifications: 'notifications',
    selectLocation: 'selectLocation',
    stylistProfileNew: 'stylistProfileNew',
    scheduledServices: 'scheduledServices',
    completedServices: 'completedServices',
    awaitingServices: 'awaitingServices',
    postReview: 'postReview',
    stylers: 'stylers',
    favoriteStylers: 'favoriteStylers',
    pastStylers: 'PastStylers',
    editProfile: 'EditProfile',
    changePassword: 'changePassword',
    payment: 'payment',
    payNow: 'payNow',
    addCard: 'addCard',
    redemptions: 'redemptions',
    locationSetting: 'locationSetting',
    promo: 'promo',
    notificationSettings: 'notificationSettings',
    liveChat: 'liveChat',
    emailCustomerSupport: 'emailCustomerSupport',
    becomeStylist: 'becomeStylist',
    canellationPolicy: 'canellationPolicy',
    legalNoticies: 'legalNoticies',
    selectAddress: 'selectAddress',
    selectStylist: 'selectStylist',
    stylistProfile: 'stylistProfile',
    confirmation: 'confirmation',
    chatScreen: 'chatScreen',
    selectdate:'selectdate',
    editProfile:'editProfile',
    confirmation:'confirmation'
  },

  provider: {
    mainTab: 'mainTab',
    homeTab: 'homeTab',
    jobDetail: 'jobDetail',
    home: 'providerHome',
    availablilityTab: 'availablilityTab',
    stylesTab: 'stylesTab',
    profileTab: 'profileTab',
    manageOngoingAvailability: 'manageOngoingAvailability',
    manageVacationTime: 'manageVacationTime',
    adjustComingHour: 'adjustComingHour',
    profile: 'Profile',
    searchClient: 'searchClient',
    services: 'services',
    selectDate: 'selectDate',
    charges: 'charges',
    businessPhoto: 'businessPhoto',
    addSkills: 'addSkills',
    editSkills: 'editSkills',
    setRate: 'setRate',
    support: 'support',
    faq: 'faq',
    liveChat: 'liveChat',
    emailCustomerSupport: 'emailCustomerSupport',
    privacyPolicy: 'privacyPolicy',
    termsAndCondition: 'termsAndCondition',
    acknowledgements: 'acknowledgements',
    chatScreen: 'chatScreen',
    Chats: 'Chats',
    styles: 'styles',
    notifications: 'notifications',
    directDeposit: 'directDeposit',
    locationSetting: 'locationSetting',
    aboutMe: 'aboutMe',
    closingMessage: 'closingMessage',
    promo: 'promo',
    accountSettings: 'accountSettings',
    changePassword: 'changePassword',
    support: 'support',
    selectWorkArea: 'selectWorkArea',
    myBusiness: 'myBusiness',
    Message: 'Message',
    bookingRequests: 'bookingRequests',
    postReview: 'postReview',
    myBusinessReview: 'myBusinessReview',
    profileUpdate:'profileUpdate',
    editpricelistt:'editpricelistt',
    editservice:'editservice'

    // mainTab: 'mainTab',
    // homeTab: 'homeTab',
    // stylesTab: 'stylesTab',
    // availablilityTab: 'availablilityTab',
    // myBusinessTab: 'myBusinessTab',
    // profileTab: 'clientProfileTab',
    // home: 'home',
    // styles: 'styles',
    // currentStyles: 'currentStyles',
    // pastStyles: 'pastStyles',
    // availablility: 'availablility',
    // manageLeaves: 'manageLeaves',
    // manageSchedule: 'manageSchedule',
    // scheduleByDate: 'scheduleByDate',
    // myBusiness: 'myBusiness',
    // profile: 'profile',
    // editProfile: 'editProfile',
    // notifications: 'notifications',
    // chats: 'chats',
    // chatScreen: 'chatScreen',
    // profile: 'profile',
    // businessPhotos: 'businessPhotos',
    // skills: 'skills',
    // addSkill: 'addSkill',
    // setRate: 'setRate',
    // editRate: 'editRate',
    // selectWorkArea: 'selectWorkArea',
    // directDeposit: 'directDeposit',
    // locationSettings: 'locationSettings',
    // aboutMe: 'aboutMe',
    // closingMessage: 'closingMessage',
    // promotion: 'promotion',
    // accountSettings: 'accountSettings',
    // changePassword: 'changePassword',
    // faq: 'faq',
    // liveChat: 'liveChat',
    // emailCustomerSupport: 'emailCustomerSupport',
    // privacyPolicy: 'privacyPolicy',
    // termsConditions: 'termsConditions',
    // acknowledgements: 'acknowledgements',
    // support: 'support',
    // bookingRequests: 'bookingRequests',
    // jobProgress: 'jobProgress',
  },
};

const tab = {
  tabBarOptions: {
    //showLabel: false,
    activeTintColor: colors.appTextColor6,
    inactiveTintColor: colors.appTextColor6,
    allowFontScaling: true,
    style: appStyles.tabBarStyle,
    activeBackgroundColor: '#00000040',
    tabStyle: {
      borderRadius: 20,
      marginHorizontal: 3,
      marginVertical: 3,
      // paddingBottom: 0,
      padding: 13,
    },
    labelStyle: [{ fontSize: fontSize.small }],
  },
  servicesTopTabBarOptions: {
    //showLabel: false,
    activeTintColor: colors.appColor1,
    inactiveTintColor: colors.appColor1,
    allowFontScaling: true,
    style: appStyles.servicesTopTabBarStyle,
    showIcon: true,
    indicatorStyle: {
      backgroundColor: colors.appColor1,
      height: height(0.4),
      borderRadius: 10,
    },
    tabStyle: { flexDirection: 'row' },
    labelStyle: [appStyles.textRegular, appStyles.textPrimaryColor],
    // activeBackgroundColor:'#FFFFFF40',
    //tabStyle:{borderRadius:20,marginHorizontal:7.5,marginVertical:2}
  },
  stylesTopTabBarOptions: {
    //showLabel: false,
    activeTintColor: colors.appTextColor6,
    inactiveTintColor: colors.appTextColor6,
    allowFontScaling: true,
    style: appStyles.stylesTopTabBarStyle,
    showIcon: true,
    indicatorStyle: {
      backgroundColor: colors.appTextColor6,
      height: height(0.5),
      borderRadius: 10,
    },
    //tabStyle: { flexDirection: 'row' },
    labelStyle: [appStyles.textRegular, appStyles.textWhite],
    //activeBackgroundColor:'#FFFFFF40',
    //tabStyle:{borderRadius:20,marginHorizontal:7.5,marginVertical:2}
  },
};

export { baseURL, mapKey, endPoints, header, routes, tab };

const styles = StyleSheet.create({
  stylesTopTabBarStyle: {
    backgroundColor: colors.appColor1,
  },
});
